name: Create CNAME

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create CNAME file
      run: |
        echo "docs.spaceb.in" >> CNAME
    - name: Commit files
      run: |
        git remote set-url origin ${{ secrets.ssh }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "create: CNAME"
    - name: Push changes
      run: |
        git fetch origin master
        git push origin HEAD:master
